/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: cealford (https://sketchfab.com/cealford)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-floor-54b0c7906b9047478aed14eb1b697f80
Title: Wooden Floor
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Floor(props) {
  const { nodes, materials } = useGLTF('/floor-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.floor_texture} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} position={[0, 0.1, 0]}/>
    </group>
  )
}

useGLTF.preload('/floor-transformed.glb')
