/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sofa.gltf --transform
Author: katjagricishina (https://sketchfab.com/katjagricishina)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sofa-03550a3529c24611a12aa158747374e0
Title: Sofa
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Sofa(props) {
  const { nodes, materials } = useGLTF('/sofa-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={0.05} position={[0, -0.75, 0]} />
    </group>
  )
}

useGLTF.preload('/sofa-transformed.glb')
